version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Install bundler
          command: gem install bundler -v 2.3.7
      - ruby/install-deps

  test:
    docker:
      - image: 'cimg/ruby:2.7'
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build


